app/app/api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("dj-auth/", views.DJAuthAPIView.as_view(), name="dj_auth"),
    path(
        "validate-stream-key/",
        views.ValidateStreamKeyView.as_view(),
        name="validate_stream_key",
    ),
    path("next-track/", views.NextTrackAPIView.as_view(), name="next_track"),
    path("sftp-auth/", views.SFTPAuthView.as_view(), name="sftp_auth"),
    path("sftp-upload/", views.SFTPUploadView.as_view(), name="fstp_upload"),
]

app/app/crazyarms/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve

urlpatterns = [
    path("", include("webui.urls")),
    path("api/", include("api.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT})]

app/app/webui/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import path, re_path

from . import views

urlpatterns = [
    re_path("^(?:|status/)$", views.StatusView.as_view(), name="status"),
    path("banlist/", views.BanListView.as_view(), name="banlist"),
    path("change-password/", views.PasswordChangeView.as_view(), name="password_change"),
    path("first-run/", views.FirstRunView.as_view(), name="first_run"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            extra_context={
                "hide_login_link": True,
                "title": "Login",
                "submit_text": "Login",
            },
            redirect_authenticated_user=True,
            template_name="webui/login.html",
        ),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("info/", views.InfoView.as_view(), name="info"),
    path(
        "set-password/<token>/",
        views.SetPasswordByEmailView.as_view(),
        name="password_set_by_email",
    ),
    path("playout-log/", views.PlayoutLogView.as_view(), name="playout_log"),
    path("profile/", views.UserProfileView.as_view(), name="profile"),
    path(
        "profile/email/<token>/",
        views.UserProfileEmailUpdateView.as_view(),
        name="profile_email_update",
    ),
    path("scheduled-shows/", views.GCalView.as_view(), name="gcal"),
    path(
        "status/autodj-request/",
        views.AutoDJRequestAJAXFormView.as_view(),
        name="autodj_request",
    ),
    path(
        "status/autodj-request/choices/",
        views.AutoDJRequestChoicesView.as_view(),
        name="autodj_request_choices",
    ),
    path("status/boot/", views.BootView.as_view(), name="boot"),
    path("status/skip/", views.SkipView.as_view(), name="skip"),
    path("zoom/", views.ZoomView.as_view(), name="zoom"),
    re_path(
        "^(?P<module>logs|websockify|telnet|sse)",
        views.nginx_protected,
        name="nginx_protected",
    ),
]

if settings.EMAIL_ENABLED:
    urlpatterns += [
        path(
            "password-reset/",
            views.PasswordResetView.as_view(),
            name="admin_password_reset",
        ),
        path(
            "password-reset/<uidb64>/<token>/",
            views.PasswordResetConfirmView.as_view(),
            name="password_reset_confirm",
        ),
    ]

app/app/autodj/models.py
import datetime
import logging
import random

import unidecode

from django.core.cache import cache
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.utils import timezone

from constance import config

from common.models import AudioAssetBase, TruncatingCharField
from crazyarms import constants

logger = logging.getLogger(f"crazyarms.{__name__}")
RANDOM_CHUNK_TRIES = 15
RANDOM_CHUNK_SIZE = 250
STOPSET_CACHE_TIMEOUT = REQUESTS_CACHE_TIMEOUT = 2 * 60 * 60
ANTI_REPEAT_CACHE_TIMEOUT = 24 * 60 * 60


def random_queryset_pick(queryset):
    model_cls = queryset.model
    id_range = model_cls.objects.aggregate(min=models.Min("id"), max=models.Max("id"))
    min_id, max_id = id_range["min"], id_range["max"]

    if min_id is None or max_id is None:
        logger.warning(f"AutoDJ couldn't generate a random {model_cls._meta.verbose_name}, no assets exist")
        return None

    # We've got our query set, we're ready to pick our track
    # Generate chunk size * number of tries to get a set potential random IDs
    random_ids = random.sample(
        range(min_id, max_id + 1),
        min(RANDOM_CHUNK_TRIES * RANDOM_CHUNK_SIZE, max_id + 1 - min_id),
    )

    # Try for assets in the potential random ID set in chunks.
    for i in range(0, len(random_ids), RANDOM_CHUNK_SIZE):
        random_ids_chunk = random_ids[i : i + RANDOM_CHUNK_SIZE]

        # Preserve random ordering in query and take the first one that exists
        random_order = models.Case(*[models.When(id=id, then=pos) for pos, id in enumerate(random_ids_chunk)])
        pick = queryset.filter(id__in=random_ids_chunk).order_by(random_order).first()
        if pick:
            return pick

    logger.warning(f"AutoDJ couldn't generate a random {model_cls._meta.verbose_name}")
    return None


def normalize_title_field(value):
    return (" ".join(unidecode.unidecode(value).strip().split())).lower()


class AudioAsset(AudioAssetBase):
    TITLE_FIELDS = ("title", "artist", "album")
    TITLE_FIELDS_PRINT_SORTED = ("artist", "album", "title")
    artist = TruncatingCharField(
        "artist",
        max_length=255,
        blank=True,
        help_text="If left empty, an artist will be generated from the file's metadata.",
    )
    album = TruncatingCharField(
        "album",
        max_length=255,
        blank=True,
        help_text="If left empty, an album will be generated from the file's metadata.",
    )
    title_normalized = TruncatingCharField(max_length=255, db_index=True)
    artist_normalized = TruncatingCharField(max_length=255, db_index=True)
    album_normalized = TruncatingCharField(max_length=255, db_index=True)

    class Meta:
        ordering = ("title", "artist", "album", "id")
        verbose_name = "audio asset"
        verbose_name_plural = "audio assets"

    def clean(self, allow_conversion=True):
        super().clean(allow_conversion=allow_conversion)

        for field in self.TITLE_FIELDS:
            if field in self.get_dirty_fields():
                setattr(
                    self,
                    f"{field}_normalized",
                    normalize_title_field(getattr(self, field)),
                )

        # Only run if there is a title + artist
        if config.ASSET_DEDUPING and self.title_normalized and self.artist_normalized:
            match = (
                AudioAsset.objects.exclude(id=self.id)
                .filter(
                    status=self.Status.READY,
                    artist_normalized=self.artist_normalized,
                    album_normalized=self.album_normalized,
                    title_normalized=self.title_normalized,
                )
                .first()
            )
            if match:
                raise ValidationError(
                    f"A duplicate audio file already exists with the same artist, title (and album): {match}"
                )

    def queue_autodj_request(self):
        requests = cache.get(constants.CACHE_KEY_AUTODJ_REQUESTS, [])
        if len(requests) >= config.AUTODJ_REQUESTS_NUM or self.id in requests:
            logger.info(f"attempted to make autodj request {self}, but queue full or request exists")
            return False
        else:
            requests.append(self.id)
            cache.set(
                constants.CACHE_KEY_AUTODJ_REQUESTS,
                requests,
                timeout=REQUESTS_CACHE_TIMEOUT,
            )
            logger.info(f"queue autodj request {self}")
            return True

    @classmethod
    def process_anti_repeat_autodj(cls, audio_asset):
        if config.AUTODJ_ANTI_REPEAT_ENABLED:
            for conf_amount, cache_key, attr in (
                (
                    config.AUTODJ_ANTI_REPEAT_NUM_TRACKS_NO_REPEAT,
                    constants.CACHE_KEY_AUTODJ_NO_REPEAT_IDS,
                    "id",
                ),
                (
                    config.AUTODJ_ANTI_REPEAT_NUM_TRACKS_NO_REPEAT_ARTIST,
                    constants.CACHE_KEY_AUTODJ_NO_REPEAT_ARTISTS,
                    "artist_normalized",
                ),
            ):
                if conf_amount > 0:
                    no_repeat_list = cache.get(cache_key) or []
                    value = getattr(audio_asset, attr)  # Skip for blank artists
                    if value:
                        no_repeat_list.insert(0, value)
                    no_repeat_list = no_repeat_list[0:conf_amount]
                    cache.set(cache_key, no_repeat_list, timeout=ANTI_REPEAT_CACHE_TIMEOUT)

        return audio_asset

    @classmethod
    def get_next_for_autodj(
        cls,
        run_with_playlist=True,
        run_no_repeat_artists=True,
        run_no_repeat_track_ids=True,
    ):
        audio_asset = playlist = None

        # Deal with autodj requests
        requests = cache.get(constants.CACHE_KEY_AUTODJ_REQUESTS)
        if requests:
            request_id = requests.pop(0)
            cache.set(
                constants.CACHE_KEY_AUTODJ_REQUESTS,
                requests,
                timeout=REQUESTS_CACHE_TIMEOUT,
            )
            try:
                audio_asset = cls.objects.get(id=request_id)
            except AudioAsset.DoesNotExist:
                logger.warnining(f"request with audio asset id = {request_id} doesn't exist")
            else:
                logger.info(f"selected {audio_asset} from autodj request queue")
                return cls.process_anti_repeat_autodj(audio_asset)

        if not config.AUTODJ_ANTI_REPEAT_ENABLED:
            # If anti-repeat is enabled, we don't run these things
            run_no_repeat_artists = run_no_repeat_track_ids = False

        # Or if they're set to 0
        if run_no_repeat_artists and config.AUTODJ_ANTI_REPEAT_NUM_TRACKS_NO_REPEAT_ARTIST <= 0:
            run_no_repeat_artists = False
        if run_no_repeat_track_ids and config.AUTODJ_ANTI_REPEAT_NUM_TRACKS_NO_REPEAT <= 0:
            run_no_repeat_track_ids = False

        queryset = cls.objects.filter(status=AudioAsset.Status.READY)
        if not queryset.exists():
            logger.warning("no assets exist, giving up early")
            return None

        if config.AUTODJ_PLAYLISTS_ENABLED:
            # Only select from active playlists with at least one uploaded audio asset in them
            playlists_with_assets = list(
                Playlist.objects.filter(is_active=True, audio_assets__status=AudioAsset.Status.READY).distinct()
            )
            if run_with_playlist and not playlists_with_assets:
                run_with_playlist = False

            if run_with_playlist:
                # Select a playlist at random, applying its weighting
                playlists = list(playlists_with_assets)
                playlist = random.choices(playlists, weights=[p.weight for p in playlists], k=1)[0]
                queryset = queryset.filter(playlists=playlist)

            elif playlists_with_assets:
                # Otherwise select from all playlists (this excludes assets not in playlists)
                queryset = queryset.filter(playlists__in=playlists_with_assets)

            else:
                # If no playlists with assets exist, we don't filter by them
                logger.warning("no playlist with assets exists, so not filtering by playlist")
        else:
            run_with_playlist = False

        if run_no_repeat_artists:
            # Exclude from repeated artists
            no_repeat_artists = cache.get(constants.CACHE_KEY_AUTODJ_NO_REPEAT_ARTISTS)
            if no_repeat_artists:
                queryset = queryset.exclude(artist_normalized__in=no_repeat_artists)

        if run_no_repeat_track_ids:
            # Exclude from repeated tracks
            no_repeat_ids = cache.get(constants.CACHE_KEY_AUTODJ_NO_REPEAT_IDS)
            if no_repeat_ids:
                queryset = queryset.exclude(id__in=no_repeat_ids)

        # We've got our query set, we're ready to pick our track randomly
        audio_asset = random_queryset_pick(queryset)
        if audio_asset is not None:
            # We found a random asset. Process it and return to either recursive calls or directly
            logger.info(
                f"selected {audio_asset} "
                f"({f'selected from playlist {playlist}' if playlist else 'did not use a playlist'})"
            )
            return cls.process_anti_repeat_autodj(audio_asset)

        # We couldn't find a track, so we need to un-apply our filters
        # There are if/elif clauses. We're recursing and we need to hit the base case
        if run_with_playlist:
            # First recurse, use all playlists instead of filtering by chosen one
            logger.warning(f"no track found in {playlist}, attempting to run with all playlists")
            audio_asset = cls.get_next_for_autodj(
                run_with_playlist=False,

app/app/broadcast/models.py
from django.db import models
from django.utils import timezone
from django.utils.formats import date_format

from huey.contrib.djhuey import revoke_by_id

from common.models import AudioAssetBase, TimestampedModel, User, after_db_commit


class BroadcastAsset(AudioAssetBase):
    UNNAMED_TRACK = "Unnamed Broadcast"
    UPLOAD_DIR = "broadcasts"

    class Meta:
        verbose_name = "scheduled broadcast asset"
        verbose_name_plural = "scheduled broadcast assets"
        ordering = ("title", "id")


class Broadcast(TimestampedModel):
    class Status(models.TextChoices):
        PENDING = "-", "to be queued"
        QUEUED = "q", "queued for play"
        PLAYED = "p", "played"
        FAILED = "f", "failed to play"

    creator = models.ForeignKey(User, verbose_name="creator", on_delete=models.SET_NULL, null=True)
    asset = models.ForeignKey(
        BroadcastAsset,
        verbose_name="broadcast asset",
        related_name="broadcasts",
        on_delete=models.CASCADE,
    )
    scheduled_time = models.DateTimeField()
    status = models.CharField(max_length=1, choices=Status.choices, default=Status.PENDING)
    task_id = models.UUIDField(null=True)

    def __init__(self, *args, **kwargs):
        self.queue_after_save = False
        super().__init__(*args, **kwargs)

    def __str__(self):
        scheduled_time = date_format(timezone.localtime(self.scheduled_time), "SHORT_DATETIME_FORMAT")
        return f"{self.asset} ({self.get_status_display()} at {scheduled_time})"

    class Meta:
        ordering = ("-scheduled_time",)
        verbose_name = "scheduled broadcast"
        verbose_name_plural = "scheduled broadcasts"

    @after_db_commit
    def queue(self):
        from .tasks import play_broadcast

        task = play_broadcast.schedule(args=(self,), eta=self.scheduled_time)
        Broadcast.objects.filter(id=self.id).update(task_id=task.id)

    def clean(self):
        if self.status == self.Status.PENDING:
            self.status = self.Status.QUEUED
            self.queue_after_save = True

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.queue_after_save:
            self.queue()

    def delete(self, *args, **kwargs):
        if self.task_id:
            revoke_by_id(self.task_id)
        return super().delete(*args, **kwargs)

app/app/webui/templates/webui/form.html
{% extends 'webui/base.html' %}

{% block content %}
{% if form %}
  {% if form_description %}
    <p>{{ form_description }}</p>
  {% endif %}

  <form method="post">
    {% csrf_token %}
    <table class="first-td-right form-table">
      {% block form_table %}
        {{ form.as_table }}
      {% endblock %}
    </table>
    <p>
      <button class="bg-green" type="submit">{{ submit_text|default:'Submit' }}</button>
      <button type="reset">Reset Form</button>
    </p>
  </form>
{% endif %}
{% endblock %}

app/app/webui/templates/webui/playout_log.html
{% extends 'webui/base.html' %}

{% block content %}

<p>
  Below is a
    {% if perms.services.view_playoutlogentry %}simplified{% endif %}
  view of
  {% if object_list.count == MAX_ENTRIES %}
    {% if perms.services.view_playoutlogentry %}<em>only</em>{% endif %}
    the latest {{ MAX_ENTRIES }}
  {% else %}
    all {{ object_list.count }}
  {% endif %}
  playout log entr{{ object_list.count|pluralize:"y,ies" }}.
  Refresh this page to get the most up-to-date data.
  {% if perms.services.view_playoutlogentry %}
  <br>
  <em>
    (For a more advanced view, head over to the
    <strong><a href="{% url 'admin:services_playoutlogentry_changelist' %}">
      Station Admin Site</a></strong>.)
  </em>
  {% endif %}
</p>

<table>
  <caption>Playout Log</caption>
  <thead>
    <tr>
      <th>#</th>
      <th>Time ({{ user.timezone }})</th>
      <th>Event Type</th>
      <th>Description</th>
      <th>Active Source</th>
  </thead>
  <tbody>
    {% for playout_log_entry in object_list %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ playout_log_entry.created|date:'SHORT_DATETIME_FORMAT' }}</td>
        <td>{{ playout_log_entry.get_event_type_display }}</td>
        <td>
          {# TODO: add playlist to logs? #}

          {# audio assets #}
          {% if config.AUTODJ_ENABLED and playout_log_entry.audio_asset_id and perms.playout.change_audioasset %}
            <a href="{% url 'admin:autodj_audioasset_change' object_id=playout_log_entry.audio_asset_id %}">{{ playout_log_entry.description }}</a>

          {# rotator assets #}
          {% elif config.AUTODJ_ENABLED and config.AUTODJ_STOPSETS_ENABLED and playout_log_entry.rotator_asset_id and perms.playout.change_audioasset %}
            <a href="{% url 'admin:autodj_rotatorasset_change' object_id=playout_log_entry.rotator_asset_id %}">{{ playout_log_entry.description }}</a>

          {# broadcast assets #}
          {% elif playout_log_entry.broadcast_asset_id and perms.broadcast.change_broadcast %}
            <a href="{% url 'admin:broadcast_broadcastasset_change' object_id=playout_log_entry.broadcast_asset_id %}">{{ playout_log_entry.description }}</a>

          {# user related #}
          {% elif user.is_superuser and playout_log_entry.user_id %}
            <a href="{% url 'admin:common_user_change' object_id=playout_log_entry.user_id %}">{{ playout_log_entry.description }}</a>

          {% else%}
            {{ playout_log_entry.description }}
          {% endif %}
        </td>
        <td>{{ playout_log_entry.active_source }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

app/app/webui/templates/webui/status.html
{% extends 'webui/base.html' %}

{% load static %}

{% block extrahead %}
{% if autodj_requests_form %}
  {{ autodj_requests_form.media.css }}
{% endif %}

{{ upcoming_status|json_script:'upcoming-status-json' }}
{{ liquidsoap_status|json_script:'harbor-status-json' }}
<script>
  {% url 'boot' as boot_url %}
  {% url 'skip' as skip_url %}
  {% url 'autodj_request' as autodj_request_url %}
  var bootUrl = '{{ boot_url|escapejs }}',
      skipUrl = '{{ skip_url|escapejs }}',
      autoDJRequestsUrl = '{{ autodj_request_url|escapejs }}',
      csrfToken = '{{ csrf_token|escapejs }}',
      perms = {
        "isSuperuser": {{ user.is_superuser|yesno:'true,false' }},
        "canBoot": {{ perms.common.can_boot|yesno:'true,false' }},
        "changeBroadcast": {{ perms.broadcast.change_broadcast|yesno:'true,false' }},
        "showAutoDJRequests": {{ autodj_requests_form|yesno:'true,false' }}
      }
  perms.showActions = perms.isSuperuser || perms.canBoot || perms.changeBroadcast
</script>
<script src="{% static 'webui/js/handlebars.min.js' %}"></script>
<script src="{% static 'webui/js/status.js' %}"></script>
{% endblock %}

{% block content %}

{% verbatim %}
<script id="harbor-status-template" type="text/x-handlebars-template">
{{#if sources}}
  <table class="first-td-right">
    <caption>Harbor Information (Live)</caption>
    <tr>
      <td width="25%"><strong>Current Stream:</strong></td>
      <td width="75%" colspan="3">
        {{#each sources}}
          {{#if this.is_current_stream}}
            <strong class="green">{{this.name}}</strong>
          {{/if}}
        {{/each}}
        <em>(see below)</em>
      </td>
    </tr>
    <tr>
      <td><strong>Current Metadata:</strong></td>
      <td colspan="3">
        {{#with metadata}}
          {{#if artist}}{{artist}}{{#if album}} - {{else}}{{#if title}} - {{/if}}{{/if}}{{/if}}
          {{#if album}}{{album}}{{#if title}} - {{/if}}{{/if}}
          {{#if title}}{{title}}{{/if}}
          {{#unless artist}}
            {{#unless album}}
              {{#unless title}}
                <em>none</em>
              {{/unless}}
            {{/unless}}
          {{/unless}}
        {{/with}}
        {{#ifEqual current_source_id source_ids.dj_harbor}}
          {{#ifNotEqual live_user.title metadata.title}}
            <br><em>Scheduled Show: {{live_user.title}}</em>
          {{/ifNotEqual}}
        {{/ifEqual}}
      </td>
    </tr>
    <tr>
      <td><strong>Time Remaining:</strong></td>
      <td colspan="3">
        {{#each sources}}
          {{#if this.is_current_stream}}
            {{#ifEqual this.id ../source_ids.dj_harbor}}
              {{#if ../live_user}}
                {{#with ../live_user}}
                  {{username}} {{#ifNotEqual username full_name}}({{full_name}}){{/ifNotEqual}}
                  authorized to stream for
                  {{#if kickoff_time}}
                    <code class="track-end" data-end="{{kickoff_time}}"></code> until kicked off
                  {{else}}
                    an unlimited amount of time
                  {{/if}}
                {{/with}}
              {{else}}
                &mdash;
              {{/if}}
            {{else}}
              {{#with (lookup ../timed_sources [id])}}
                <code class="track-end" data-end="{{this}}"></code> remaining of current track
              {{else}}
                &mdash;
              {{/with}}
            {{/ifEqual}}
          {{/if}}
        {{/each}}
      </td>
    </tr>
    <tr>
      <td><strong>Server Uptime:</strong></td>
      <td width="25%"><code class="since-timer" data-since="{{server_info.start_time}}"></code></td>
      <th width="25%" class="right-text"><strong>
        <a href="https://dtcooper.github.io/crazyarms" target="_blank">Crazy Arms</a> Version:
      </strong></td>
      <td width="25%"><code>{% endverbatim %}{{ crazyarms_version }}{% verbatim %}</code></td>
    </tr>
  </table>
  <table>
    <caption>Harbor Sources (Live)</caption>
    <thead>
      <tr>
        <th{{#if showActions}} width="12%"{{/if}}>Priority</th>
        <th{{#if showActions}} width="31%"{{/if}}>Source Name</th>
        <th {{#if showActions}}width="26%"{{else}}colspan="2"{{/if}}>Active</th>
        {{#if showActions}}
          <th width="30%">Actions</th>
        {{/if}}
      </tr>
    </thead>
    <tbody>
      {{#each sources}}
        {{#with this}}
          <tr{{#if is_current_stream}} class="green bold"{{/if}}>
            <td>{{priority}}</td>

            <td>
              {{name}}
              {{#ifEqual id ../source_ids.dj_harbor}}
                {{#if ../live_user}}
                  {{#with ../live_user}}
                    <span class="green">&mdash; DJ currently connected</span>
                    <ul>
                      <li>User: {{username}} {{#ifNotEqual username full_name}}({{full_name}}){{/ifNotEqual}}</li>
                      <li>Connected for <code class="since-timer" data-since="{{connected_since}}"></code></li>
                      {{#if kickoff_time}}
                        <li class="red">Kicked off in <code class="track-end" data-end="{{kickoff_time}}"></code></li>
                      {{/if}}
                    <ul>
                  {{/with}}
                {{else}}
                  &mdash; No user connected
                {{/if}}
              {{/ifEqual}}
            </td>

            <td
            {{#if is_current_stream}}
              >
              Active &amp; streaming
              {{#with (lookup ../timed_sources [id])}}
                <br>
                <code class="track-end" data-end="{{this}}"></code> remaining of track
              {{/with}}
            {{else}}
              {{#if is_active}}
                class="orange">
                Active, not streaming<br>
                (priority too low)
              {{else}}
                class="red">Inactive (or silent)
              {{/if}}
            {{/if}}
            </td>

            {{#if ../showActions}}
              <td>
                {{#ifContains ../skippable_sources id}}
                  {{#if ../changeBroadcast}}
                    {{#if is_active}}
                      {{#if is_current_stream}}
                        <button class="skip-btn bg-orange" data-name="{{name}}" data-id="{{id}}"><strong><u>SKIP</u></strong> what's currently playing</button>
                      {{/if}}
                    {{/if}}
                  {{/if}}
                {{/ifContains}}
                {{#ifEqual id ../source_ids.dj_harbor}}
                  {{#with ../live_user}}
                    {{#if ../../canBoot}}
                      <button class="boot-btn" data-time="60" data-text="1 minute" data-name="{{username}}" data-id="{{user_id}}">
                        Ban {{username}} for 1 minute
                      </button>
                      <br>
                      <button class="boot-btn bg-orange" data-time="900" data-text="15 minutes" data-name="{{username}}" data-id="{{user_id}}">
                        Ban {{username}} for 15 minutes
                      </button>
                      <br>
                      <button class="boot-btn bg-orange" data-time="3600" data-text="1 hour" data-name="{{username}}" data-id="{{user_id}}">
                        Ban {{username}} for 1 hour
                      </button>
                    {{/if}}
                    {{#if ../../isSuperuser}}
                      <br>
                      <button class="boot-btn bg-red" data-time="permanent" data-text="permanently" data-name="{{username}}" data-id="{{user_id}}">
                        Ban {{username}} <strong><u>PERMANENTLY</u></strong><br>
                        (sets harbor authorization to <em>never</em>)
                      </button>
                    {{/if}}
                  {{/with}}

                {{/ifEqual}}
              </td>
            {{/if}}
          </tr>
        {{/with}}
      {{/each}}
    </tbody>
  </table>
{{else}}
  <p class="error">The harbor appears to be down. Please try again later.</p>
{{/if}}
</script>
{% endverbatim %}
<div id="harbor-status"></div>

{% verbatim %}
<script id="upcoming-status-template" type="text/x-handlebars-template">
<table class="first-td-right">
  <caption>Upcoming Broadcasts</caption>
  {{#if this}}
    <thead>
      <tr>
        <th width="25%">When</th>
        <th width="55%">Title</th>
        <th width="20%">Type</th>
      </tr>
    </thead>
    <tbody>
      {{#each this}}
        <tr>
          <td>{{#ifEqual date "now"}}<strong class="green">Now!</strong>{{else}}{{date}}{{/ifEqual}}</td>
          {{! we're not sure whether DJs are playing are not, even if the DJ connected is the one, so we use
              the copy "scheduled" for live... confusing, I know }}
          <td>{{#ifEqual date "now"}}<strong class="green">Currently {{#ifEqual type "live"}}scheduled{{else}}airing{{/ifEqual}}:</strong> {{/ifEqual}}{{title}}</td>
          <td>
            {{#ifEqual type "scheduled"}}
              Prerecorded Broadcast
            {{/ifEqual}}
            {{#ifEqual type "live"}}
              Live DJ
            {{/ifEqual}}
          </td>
        </tr>
      {{/each}}
    </tbody>
  {{else}}
    <th><em>There are no upcoming broadcasts scheduled.</em></th>
  {{/if}}
</table>
</script>
{% endverbatim %}
<div id="upcoming-status"></div>

{% if autodj_requests_form %}
  <table class="autodj-requests-table first-td-right">
    <caption>AutoDJ Requests</caption>
      <tr>
        <td width="15%">Your Request:</td>
        <td width="85%">{{ autodj_requests_form.asset }}</td>
      </tr>
      <tr>
        <td colspan="2" class="center-text">
          <button class="request-btn bg-green">Submit Request to be Queued</button>
        </td>
      </tr>
  </table>
  {{ autodj_requests_form.media.js }}
{% endif %}
{% endblock %}